config/routes.rb
Rails.application.routes.draw do
  resources :valhallas
  resources :diets
  resources :exercises
  resources :vikings
  resources :sessions
  resources :viking_exercises, only:[:create]
  get "/login", to: "sessions#new"
  delete '/viking_exercises', to: 'viking_exercises#destroy', as: 'destroy_viking_exercises'
  delete '/sessions', to: 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diet.rb
class Diet < ApplicationRecord
	has_many :vikings
end

app/models/exercise.rb
class Exercise < ApplicationRecord

	has_many :viking_exercises
	has_many :vikings, through: :viking_exercises
	validates_presence_of :name, :exercise_type, :time, :calories, :instruction_link
	validates :calories, numericality: { greater_than: 0}
	validates :time, numericality: { greater_than: 0}


end

app/models/valhalla.rb
class Valhalla < ApplicationRecord
	has_many :viking_valhallas
	has_many :vikings, through: :viking_valhallas
end

app/models/viking.rb
class Viking < ApplicationRecord

	has_secure_password

	belongs_to :diet

	has_many :viking_exercises
	has_many :exercises, through: :viking_exercises

	has_many :viking_valhallas
	has_many :valhallas, through: :viking_valhallas

	validates_presence_of :name, :age, :weight, :body_fat, :residence ,:calories, :image_url
	validates :password, presence: true, confirmation: true
	validates :calories, numericality: { greater_than: 0}
	validates :weight, numericality: { greater_than: 0}
	validates :age, numericality: { greater_than: 0}
	validates :body_fat, numericality: { greater_than: 0}
	validates :diet_id, numericality: { greater_than: 0, less_than:4}





	def total_calories
		self.exercises.sum(:calories)
	end

	def total_time
		self.exercises.sum(:time)
	end

	def calc_fat
		fat= (self.diet.fat/100)
		self.calories*fat
	end

	def calc_protein
		protein= (self.diet.protein/100)
		self.calories*protein
	end

	def calc_carbs
		carbs= (self.diet.carbs/100)
		self.calories*carbs
	end

	def my_viking_exercises
		VikingExercise.all.select do |viking_exercise|
			viking_exercise.viking == self
		end
	end

end

app/models/viking_exercise.rb
class VikingExercise < ApplicationRecord
	belongs_to :viking
	belongs_to :exercise

	def exercise_name
		self.exercise.name
	end

	def exercise_calories
		self.exercise.calories
	end

	def exercise_time
		self.exercise.time
	end

end

app/models/viking_valhalla.rb
class VikingValhalla < ApplicationRecord
	belongs_to :viking
	belongs_to :valhalla
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :define_logged_in_viking

	def redirect_if_not_logged_in
		if !session[:signed_in_viking_id]
			redirect_to login_path
		end
	end

	private
	def define_logged_in_viking

		if(session[:signed_in_viking_id])
			@logged_in_viking = Viking.find(session[:signed_in_viking_id])
		else
			@logged_in_viking = Viking.new
			@logged_in_viking.name = 'Loki'
		end
		
	end

end

app/controllers/diets_controller.rb
class DietsController < ApplicationController

	def index
		@diets = Diet.all
	end

	def show 
		@diet = Diet.find(params[:id])
	end


end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :current_exercise, only: [:show, :edit, :update, :destroy]
  before_action :redirect_if_not_logged_in, only: [:new, :edit]



  def index
    @exercises = Exercise.all
  end

  def show
    session[:current_exercise_id] = @exercise.id
  end

  def new
    @exercise = Exercise.new(flash[:form_values])
  end

  def create
    @exercise = Exercise.new(exercise_params)
    if @exercise.valid?
      @exercise.save
      VikingExercise.create(viking_id:session[:signed_in_viking_id], exercise:@exercise)
      redirect_to exercises_path
    else
      flash[:error_message] = @exercise.errors.full_messages.join(', ')
      flash[:form_values] = exercise_params
      redirect_to new_exercise_path
    end
  end

  def edit

  end

  def update
    if @exercise.update(exercise_params)
      redirect_to @exercise
    else
      byebug
      flash[:error_message] = @exercise.errors.full_messages.join(', ')
      redirect_to edit_exercise_path
    end


  end

  def destroy
    @exercise.destroy

    redirect_to exercises_path
  end

  private

  def exercise_params
    params.require(:exercise).permit(:name, :exercise_type, :time, :calories, :instruction_link)
  end


  def current_exercise
    @exercise = Exercise.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		viking = Viking.find_by(name: params[:name])

		if viking && viking.authenticate(params[:password])
			session[:signed_in_viking_id] = viking.id
			redirect_to viking
		else
			flash[:error] = "Incorrect Username/Password Combination"
  			redirect_to login_path
		end
	end


	def destroy
		reset_session
		redirect_to vikings_path
	end

end

app/controllers/valhallas_controller.rb
class ValhallasController < ApplicationController
  before_action :current_valhalla, only: [:show, :edit, :update, :destroy]

  def index
    @client = GooglePlaces::Client.new(ENV['my_api_key'])
    @valhallas = Valhalla.all
    @temps = @client.spots_by_query("#{@logged_in_viking.residence}", :types => ['gym', 'park'], detail: true)
  end


  def show

  end

  def new
    @valhalla = Valhalla.new
  end

  def create
    @valhalla = Valhalla.create(valhalla_params)

    redirect_to @valhalla
  end

  def edit

  end

  def update
    @valhalla.update(valhalla_params)

    redirect_to @valhalla
  end

  def destroy
    @valhalla.destroy

    redirect_to valhallas_path
  end

  private

  def valhalla_params
    params.require(:valhalla).permit(:name)
  end


  def current_valhalla
    @valhalla = Valhalla.find(params[:id])
  end

end

app/controllers/viking_exercises_controller.rb
class VikingExercisesController  < ApplicationController
  before_action :redirect_if_not_logged_in, only: [:create, :destroy]

  def create
    VikingExercise.create(viking_id:session[:signed_in_viking_id], exercise_id:session[:current_exercise_id])
    redirect_to exercises_path
  end

  def destroy
    viking_exercise = VikingExercise.find(params[:viking_exercise_id])
    viking_exercise.destroy
    redirect_to viking_exercise.viking
  end

end

app/controllers/vikings_controller.rb
class VikingsController < ApplicationController

	before_action :current_viking, only: [:show, :edit, :update, :destroy]
	# before_action :redirect_if_not_logged_in, only: [:index]

	def index
		@vikings = Viking.all
	end

	def new
		@viking = Viking.new
	end

	def show

	end

	def edit
		#byebug
		if params[:id].to_i != @logged_in_viking.id
			render :show
		end

	end


	def create
		@viking = Viking.new(viking_params)

		if @viking.save
			redirect_to @viking
		else
			error_array = @viking.errors.full_messages.join(', ')
			error_array.sub!("Diet must be less than 4", "Viking eat MEAT")
			flash[:error_message] = error_array
			redirect_to new_viking_path
		end
	end

	def update

		if @viking.update(viking_params)
			redirect_to @viking
		else
			error_array = @viking.errors.full_messages.join(', ')
			error_array.sub!("Diet must be less than 4", "Viking eat MEAT")
			flash[:error_message] = error_array
			redirect_to edit_viking_path
		end
	end

	def destroy
		@viking.destroy

		redirect_to vikings_path
	end


	private

	def viking_params
		params.require(:viking).permit(:name, :password, :password_confirmation, :age, :weight, :body_fat, :residence, :calories, :image_url, :diet_id, exercise_ids:[], valhalla_ids:[])
	end


	def current_viking
		@viking = Viking.find(params[:id])
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/valhallas_helper.rb
module ValhallasHelper
end

app/helpers/vikings_helper.rb
module VikingsHelper
end

app/views/diets/index.html.erb
<h2>All Diets</h2>
<ul class="list-group list-group-flush">

<% @diets.each do |diet| %>
	<% if diet.id<4 %>
		<li class="list-group-item">
			<%= link_to diet.diet_type, diet %>
		</li>
	<% end %>
<% end %>
</ul>

app/views/diets/show.html.erb
<ul>
	<li>Diet Type: <%= @diet.diet_type %></li>
	<li>Carbohydrate: <%= @diet.carbs %>%</li>
	<li>Protein: <%= @diet.protein %>%</li>
	<li>Fat: <%= @diet.fat %>%</li>
</ul>

app/views/exercises/_form.html.erb
<div class="text-danger"><%= flash[:error_message] %></div>

<%= form_with model: @exercise do |form| %>
  <div class="form-group col-md-6">
    <%= form.label :name%>
    <%= form.text_field :name, class:"form-control"%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :exercise_type%>
    <%= form.text_field :exercise_type, class:"form-control"%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label "Time (mins)"%>
    <%= form.number_field :time, class:"form-control"%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :calories%>
    <%= form.number_field :calories, class:"form-control"%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :instruction_link%>
    <%= form.text_field :instruction_link, class:"form-control"%>
  </div>
  <%= form.submit  class:'btn btn-primary'%>
<% end %>

app/views/exercises/edit.html.erb
<%= render 'form' %>

app/views/exercises/index.html.erb
<h2>Exercises</h2>
<ul class="list-group list-group-flush">
  <% @exercises.each do |exercise| %>
    <li class="list-group-item"> <%= link_to exercise.name, exercise %> </li>
  <% end %>
</ul>
</br>
<div >
  <% if session[:signed_in_viking_id] %>
  <%= link_to "Add Exercise", new_exercise_path, class:"btn btn-secondary" %>
  <% end %>
</div>

app/views/exercises/show.html.erb
<h1> <%= @exercise.name %> </h1>
<p> <strong>Exercise Type: </strong><%= @exercise.exercise_type %> </p>
<p> <strong>Time (mins): </strong><%= @exercise.time %> </p>
<p> <strong>Calories: </strong><%= @exercise.calories %> </p>
<p> <%= @exercise.instruction_link %> </p>
</br>
<% if session[:signed_in_viking_id] %>
<p>
  <%= link_to "Edit Exercise",edit_exercise_path, {class:"btn btn-dark"}%>
  <%= link_to "Add Exercise to Profile", viking_exercises_path, {method:'create', class:"btn btn-primary"}%>
</p>
<% end %>
</br>
<p>  <%= link_to "Back to exercises", exercises_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VikingFitness</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="icon" type="image/png" href="/assets/viking_logo_small.png">
  </head>

  <nav class="navbar navbar-expand navbar-dark bg-dark">
  <a class="navbar-brand" href="/vikings"> <img class="img-fluid" src="/assets/viking_logo_small.png"></a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Exercises", exercises_path, {class:'nav-link'} %>
      </li>
      <li class="nav-item">
        <%= link_to "Diets", diets_path, {class:'nav-link'} %>
      </li>
      <% if session[:signed_in_viking_id] %>
        <li class="nav-item">
          <%= link_to "Valhallas", valhallas_path, {class:'nav-link'} %>
        </li>
      <% end %>
    </ul>
    <div class=" my-2 my-md-0">
      <% if session[:signed_in_viking_id] %>
        <%= link_to "Viking's Home", @logged_in_viking, {class:'btn btn-secondary '} %>
        <%= link_to 'Viking Out', sessions_path, {method: 'delete', class:'btn btn-primary '} %>
      <% else %>
        <%= link_to "New Viking", new_viking_path, {class:'btn btn-secondary '} %>
        <%= link_to 'Viking Log In', new_session_path, {class:'btn btn-primary '} %>
      <% end %>
      <!-- <input class="form-control" type="text" placeholder="Search"> -->
    </div>
  </div>
</nav>

  <body class="container ">

    <% if session[:signed_in_viking_id] %>
      <p>Welcome, <%= @logged_in_viking.name %></p>
    <% end %>

    <%= yield %>



  </body>

<footer class="font-small footer bg-dark pt-4 text-secondary">
    <div class=" container-fluid text-center text-md-left">
      <div class="row">

        <!-- Grid column -->
        <div class="col-md-6 mt-md-0 mt-3">

          <!-- Content -->
          <h5 >Viking Motto</h5>
          <p>“I have no interest in peace. Peace is a dirty word.” - Ivar</p>

        </div>
        <!-- Grid column -->

        <hr class="clearfix w-100 d-md-none pb-3">

        <!-- Grid column -->
        <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="">Exercise Links</h5>

            <ul class="list-unstyled">
              <li>
                <a href="https://www.bodybuilding.com/exercises/!">Body Building Exercises</a>
              </li>
              <li>
                <a href="https://www.yogajournal.com/poses">Yoga Poses</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 mb-md-0 mb-3">

            <!-- Links -->
            <h5 class="">Viking Related Articles</h5>

            <ul class="list-unstyled">
              <li>
                <a href="https://www.bodybuilding.com/fun/arnold-schwarzenegger-blueprint-trainer-mass-training.html">Arnold Schwarzenegger Blueprint</a>
              </li>
              <li>
                <a href="https://warontherocks.com/2015/05/how-to-take-over-a-small-country-in-10-easy-steps/">Taking a Country in 10 easy steps</a>
              </li>
            </ul>

          </div>
          <!-- Grid column -->

      </div>
      <!-- Grid row -->

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2018 Copyright:
      <a href="/vikings"> Viking Fitness</a>
    </div>

  </footer>
</html>

app/views/valhallas/index.html.erb
<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['my_api_key'] %>
    &q=<%= @logged_in_viking.residence %>" allowfullscreen>
</iframe>

<br>
<!--
<%= @temps %>

 -->
 <br>
 <h2>Valhallas In <%= @logged_in_viking.name%>'s Vicinity</h2>

<ul class="list-group list-group-flush">
<% @temps.each do |location| %>
	<li class="list-group-item"><%= link_to location.name, location.website, target: :_blank %></li>
<% end %>
</ul>

app/views/vikings/_form.html.erb
<div class="text-danger"><%= flash[:error_message] %></div>
<%= form_with model: @viking do |form| %>
  <div class="form-group col-md-6">
    <%= form.label :name%>
    <%= form.text_field :name, class:"form-control"%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :password%>
    <%= form.password_field :password, class:"form-control"%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :age %>
    <%= form.number_field :age, class:"form-control"%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label "Weight (lbs)"%>
  	<%= form.number_field :weight, {:step => 'any', class:"form-control"} %>
  </div>
  <div class="form-group col-md-6">
    <%= form.label "Body Fat (%)" %>
  	<%= form.number_field :body_fat, {:step => 'any', class:"form-control"}%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :residence %>
  	<%= form.text_field :residence, class:"form-control"%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label :calories %>
  	<%= form.number_field :calories, {:step => 'any', class:"form-control" }%>
  </div>
  <div class="form-group col-md-6">
    <%= form.label "GIF URL" %>
  	<%= form.text_field :image_url, class:"form-control"%>
  </div>

  <div class="form-group col-md-6"">
    <%= form.label "Diet" %>
  	<%= form.select :diet_id, Diet.all.map{|diet| [diet.diet_type, diet.id]} , {}, class:"form-control" %>
  </div>

	<%= form.submit class:"btn btn-secondary" %>

<% end %>

app/views/vikings/edit.html.erb
<%= image_tag (@viking.image_url) %>
<br>
<%= render 'form' %>

app/views/vikings/index.html.erb
<% if session[:signed_in_viking_id] %>
	<h2>All Other Vikings</h2>
<% else %>
	<h2>All Vikings</h2>
<% end %>

<% vikingsfixed = @vikings.select {|viking| viking.id != session[:signed_in_viking_id]} %>

<ul class="list-group list-group-flush">
<% vikingsfixed.each do |viking| %>
	<li class="list-group-item">
		<%= link_to viking.name, viking %>
	</li>
	<% end %>
</ul>

app/views/vikings/new.html.erb
<%= render 'form' %>

app/views/vikings/show.html.erb
<h2>
  <%= @viking.name %>
  <% if @viking.id == session[:signed_in_viking_id] %>
    <span><%= link_to "Edit Viking", edit_viking_path%></span>
  <% end %>
</h2>

</br>

<div class="container">
  <div class="row h-100">
    <div class="col-sm">
      <%= image_tag (@viking.image_url), {class:"img-fluid "} %>
    </div>
    <div class="col-sm my-auto mx-auto">
      <p><strong>Age:</strong> <%= @viking.age %></p>
      <p><strong>Weight (lbs):</strong> <%= @viking.weight %></p>
      <p><strong>Body Fat (%):</strong> <%= @viking.body_fat %></p>
      <p><strong>Calories:</strong> <%= @viking.calories %></p>
      <p><strong>Diet:</strong> <%= link_to @viking.diet.diet_type, @viking.diet %></p>
    </div>
  </div>
</div>

</br>
</br>

<div class="container">
  <div class="row">
    <div class="col-md-9">
      <table class="table">
        <tr>
          <th>Macros</th>
          <td class="text-center">Calories to use based on:<strong><%=@viking.diet.diet_type%></strong></td>
        </tr>
        <tr>
          <th>Protein</th>
          <td class="text-center"><%=@viking.calc_protein%></td>
        </tr>
        <tr>
          <th>Carbs</h>
          <td class="text-center"><%=@viking.calc_carbs%></td>
        </tr>
        <tr>
          <th>Fats</th>
          <td class="text-center"><%=@viking.calc_fat%></td>
        </tr>
      </table>

    </div>
  </div>
</div>

</br>

<table class="table">
  <tr>
    <th>Exercise</th>
    <th>Calories Burned</th>
    <th>Elapsed Time (mins)</th>
  </tr>
  <% @viking.my_viking_exercises.each do |viking_exercise| %>
  <tr>
    <td><%= link_to viking_exercise.exercise_name, viking_exercise.exercise %> </td>
    <td><%= viking_exercise.exercise_calories %></td>
    <td><%= viking_exercise.exercise_time %></td>
    <% if @viking.id == session[:signed_in_viking_id] %>
      <td>
        <form method="post" action= <%= destroy_viking_exercises_path %> >
          <input type="hidden" name="_method" value="delete">
          <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
          <input type="hidden" name="viking_exercise_id" value="<%=viking_exercise.id%>">
          <input class="btn-secondary" value="Delete" type="submit">
        </form>
      </td>
      <% end %>
  </tr>
  <% end %>
  <tr class="font-weight-bold" >
    <td><%= "Total" %> </td>
    <td><%= @viking.total_calories %></td>
    <td><%= @viking.total_time %></td>
  </tr>
</table>


<% if @logged_in_viking.name == "Ivar the Boneless" && @viking.name == "Ivar the Boneless" %>
  <%= image_tag ('https://78.media.tumblr.com/b03e3d641264d641a21f448c3697f78e/tumblr_p1gn0ajGLH1qc7d45o1_500.gif') %>

<% end %>
<div class="container">
  <div class="row">
    <div class="col ">
      <% if session[:signed_in_viking_id] %>
      <%= link_to "Add New Exercise to Viking", new_exercise_path, class:"btn btn-secondary " %>
      <% end %>
    </div>
  </div>
</div>